### ISSUE TITLE
JS usage?

### ISSUE THREAD

**Issue by corysimmons** [shelljs/shx#103]
I only see CLI and npm script usage. Is ShellJS for JS and shx is for CLI?

**Comment by nfischer** [comment]
Yeah, that's the idea. Shx exposes ShellJS implementations to the commandline.

- ShellJS: good for writing long scripts, all in JS, running via NodeJS (`node myScript.js`)
- Shx: good for writing one-off commands in npm package scripts (like `"clean": "shx rm -rf out/"`)

**Comment by nfischer** [comment]
Closing this for now. Ping this thread if you need further clarification 😄

**Comment by corysimmons** [comment]
Nice, thank you.

I just noticed there is a spot for this in the ShellJS README. Maybe add exactly what you wrote above in this README as well? I ended up here because ShellJS was like "USE SHX FOR COMMANDS" and I was like "I want commands!" then I got here and was like "Wait, how is this different from ShellJS?"

**Comment by nfischer** [comment]
@corysimmons if you have some idea of what would make the docs more helpful, I'll gladly look over a pull request :smile:

**Comment by corysimmons** [comment]
haha, no problem.

https://github.com/shelljs/shx/pull/104
