### ISSUE TITLE
sed does not accept input from pipes

### ISSUE THREAD

**Issue by bardiharborow** [shelljs/shx#108]
`shx echo hello | shx sed 'hello' 'hola'` crashes with `sed: no files given` despite the `sed` command [appearing to accept](https://github.com/shelljs/shelljs/blob/master/src/sed.js#L39) input from pipes.

**Comment by nfischer** [comment]
Thanks for reporting this! What version of shx are you using? This was a recent feature in shx

**Comment by bardiharborow** [comment]
Ah. Stupidly I was running an older version, but this still occurs in 0.2.1, though with a slightly longer error.

```
sed: no files given
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
```

**Comment by nfischer** [comment]
I see no issues:

```bash
$ shx echo 'foolish' | shx sed 's/foo/bar/'
barlish
```

Remember the correct `sed` syntax on the newer versions of `shx` (`sed` was broken on older versions)
