### ISSUE TITLE
sed does not accept a blank replacement string

### ISSUE THREAD

**Issue by bardiharborow** [shelljs/shx#109]
After upgrading to shx 0.2.1, i.e. a version with the fixed sed syntax, I can't replace strings with a blank string. The issue is likely in [these regex](https://github.com/shelljs/shx/blob/master/src/shx.js#L65-L69).

```bash
shx echo 'foobar' | shx sed 'bar' '' # previous syntax, returned 'foo'
shx echo 'foobar' | shx sed 's/bar/lish/' # returns 'foolish'
shx echo 'foobar' | shx sed 's/bar/ /' # returns 'foo '
shx echo 'foobar' | shx sed 's/bar//' # crashes with 'sed: invalid replacement string'
echo 'foobar' | sed 's/bar//' # returns 'foo'
```

**Comment by nfischer** [comment]
Ah, I can reproduce `shx sed 's/bar//'`. Everything else is working as intended. Thanks for reporting this, I'll look into it.
