### ISSUE TITLE
Command substitution feature

### ISSUE THREAD

**Issue by scottmas** [shelljs/shx#112]
To write reasonably complex cross platform scripts, command substitution helps a ton. As a trivial example in package.json
```
shx rm $(shx pwd)/node_modules
```
I'm not familiar with the internals of shx, but it does seem like this could be tricky because it would require starting up potentially many sub-shells.

**Comment by nfischer** [comment]
@scottmas Thanks for the feature request!

While I agree this feature would be awesome, I think it may be a bit out of the scope of this project. Here are some recommended workarounds though:

 1. For trivial examples like the one above, you don't even need subshells: `shx rm -rf node_modules/` will work just fine :smile: 
 2. For trickier cases, you can write short scripts with shelljs:

    ```bash
    $ cat scripts/delete-stuff.js
    #!/usr/bin/env node
    var shell = require('shelljs');
    shell.rm('-rf', process.cwd() + '/node_modules/');
    $ node scripts/delete-stuff.js
    ```

**Comment by nfischer** [comment]
I'm going to close this. I think tricky cases can be reasonably handled with ShellJS scripts.
