### ISSUE TITLE
Fails trying to utilise the new script-shell npm config

### ISSUE THREAD

**Issue by danielbayley** [shelljs/shx#117]
The release of npm 5.1.0 [introduced] the ability to set a different shell for running package.json `scripts`, so I thought a cool idea would be to do:
`npm config set script-shell node_modules/.bin/shx`…

But for some reason it doesn't work and I'm not sure why?
~~~ ini
# .npmrc
script-shell = node_modules/.bin/shx
~~~
~~~ js
// package.json
"scripts": {
  "test": "echo something" // fails! :/
}
~~~
~~~ sh
> npm test
Error: Missing ShellJS command name

shx: A wrapper for shelljs UNIX commands.

Usage: shx <command> [options]

Example:

    $ shx ls .
    foo.txt
    bar.txt
    baz.js
    $ shx rm -rf *.txt
    $ shx ls .
    baz.js

Commands:

    - cat
    - chmod
    - cp
    - echo
    - tempdir
    - pwd
    - ls
    - find
    - grep
    - head
    - ln
    - mkdir
    - rm
    - mv
    - sed
    - sort
    - tail
    - test
    - touch
    - uniq
    - which
    - error
    - help

npm ERR! Test failed.  See above for more details.
~~~

If this worked I could finally [almost] pretend Windows doesn't exist as far as npm `scripts` are concerned, without even having to prefix every script command with `shx`, yet still support those unfortunate users…

[introduced]: https://github.com/npm/npm/pull/16687

**Comment by nfischer** [comment]
I agree with @danielbayley's [comment](https://github.com/shelljs/shx/pull/118#issuecomment-315641219). dthree/cash is a better solution for this, so I'm closing this issue.
