### ISSUE TITLE
Feature: Symbolic Links

### ISSUE THREAD

**Issue by ilyaigpetrov** [shelljs/shx#119]
I need to create a symbolic to a relative folder. Here is how I do it with windows in mind:
```js
const dirFileOrJunction = 'dir';
fs.symlink(targetPath, linkPath, dirFileOrJunction, (err) => {

  if(!err) {
    return;
  }

  if (!process.platform.startsWith('win')) {
    throw err;
  }

  // Error on Windows
  child_process.exec(`mklink /D ${linkPath} ${targetPath}`, (err, stdout, stderr) => {

    if (!err) {
        return;
    }
    // Try junction (will be absolute).
    child_process.execSync(`mklink /J ${linkPath} ${targetPath}`);

  });

})
```

**Comment by nfischer** [comment]
`ln -s`?

**Comment by ilyaigpetrov** [comment]
@nfischer, right, `ln -s`.

**Comment by nfischer** [comment]
No, I mean `shx ln -s foo bar` should work, does it not?

**Comment by ilyaigpetrov** [comment]
Yes, it works on Linux, Windows yet to test. Couldn't find any documentation about it. Thanks.

**Comment by nfischer** [comment]
Documentation is under the shelljs repo. If `shell.ln('-s', 'foo', 'bar')` doesn't work on Windows, please file a bug against that repo.
