### ISSUE TITLE
`shx echo -n aaa` shows `-n aaa`

### ISSUE THREAD

**Issue by exKAZUu** [shelljs/shx#129]
### Node version (or tell us if you're using electron or some other framework):

v9.11.1

### Shx version (the most recent version/Github branch you see the bug on):

0.2.2

### Operating system:

Windows 10

### Description of the bug:

`shx echo -n aaa` shows `-n aaa`.

**Comment by nfischer** [comment]
Can repro. I'm guessing from https://github.com/shelljs/shelljs/issues/855 that this is a bug in `shx` code.

I have no issue using `shx rm -f ...`, so this only affects `echo`? Strange...

**Comment by nfischer** [comment]
Confirmed this works on master. I'll cut a new minor release.

**Comment by nfischer** [comment]
Released in v0.3.0 :tada:

**Comment by exKAZUu** [comment]
Confirmed it works well. Thanks!
