### ISSUE TITLE
Switch this to use shelljs as a git submodule (for now)

### ISSUE THREAD

**Issue by nfischer** [shelljs/shx#13]
Since we're planning to release this with v0.7, it makes more sense to have shelljs included as a submodule (since master is most of the way to v0.7).

Once v0.7 lands, we can swap out the submodule for a regular npm dependency. If all the tests pass, we can release it.

**Comment by levithomason** [comment]
What is the advantage to the submodule vs an npm dep here?

**Comment by nfischer** [comment]
@levithomason the advantage (for right now) is that the submodule can be more up-to-date than the npm dep. The master branch has progressed quite a bit from v0.6. Since we're trying to get this project released as soon as v0.7 comes out, we'll have a smoother transition if we develop against shelljs master branch, vs. against shelljs v0.6.

This is only a temporary change, since once v0.7 is actually released, we'll want to switch to that instead of doing the git submodule.

The alternative is that we keep it as-is and just do a little bit more work once v0.7 comes out. Not the worst thing in the world.

**Comment by levithomason** [comment]
What about `npm i shelljs/shelljs -S`, installing the dep from the latest master?  Any update to master on shelljs can be instantly installed.  In my experience, submodules are more of a pain to manage.  If we are consider this for a short term, I'd like to suggest considering the install from github approach.

What say ye?

**Comment by ariporad** [comment]
I think we should do that, because ideally once 0.7 is released we'll want to keep testing master. Plus, may as well keep everything as npm.

**Comment by nfischer** [comment]
Ah, didn't know about that option. That sounds good to me. We should switch to v0.7 once it gets released though, for stability's sake.

**Comment by levithomason** [comment]
Absolutely, we def don't want to ship anything with a direct github install.  Especially without a commit sha ref.  I'll get a PR for this.
