### ISSUE TITLE
Regex support for forward slashes in sed

### ISSUE THREAD

**Issue by pithyless** [shelljs/shx#136]
`shx v 0.3.0`:

I'm trying to build a cross-platform npm-script and I'm seeing an issue with directory path separators (unix `/` vs windows `\`). I thought I could use `sed` as a workaround, but hit the following issue:

```
❯ echo '{"js\\foo.js": "js\\foo-1234.js"}' | sed 's/\\/\//g'
{"js/foo.js": "js/foo-1234.js"}

❯ echo '{"js\\foo.js": "js\\foo-1234.js"}' | npx shx sed 's/\\/\//g'
.../node_modules/shx/lib/shx.js:105
        newArgs.push(new RegExp(regexString, regexFlags));
                     ^
SyntaxError: Invalid regular expression: /\/\/: \ at end of pattern
    at new RegExp (<anonymous>)
```

**Comment by nfischer** [comment]
@pithyless fix is released in v0.3.1, let me know if you find any related bugs.
