### ISSUE TITLE
curl / wget

### ISSUE THREAD

**Issue by cyrilchapon** [shelljs/shx#141]
hey :)

I'm using shx for most administrative tasks in my package.json scripts.

I'm writing a serverless function, and I'd like to test it brutally through a curl request.

I'm facing the issue of not-writing-a-script-just-for-this, and I'd like to do this portably (env agnosticly).

I think this would be a great addition to have a curl / wget - like commend 😄

**Comment by cyrilchapon** [comment]
Sorry, added a +1 inside shelljs

**Comment by nfischer** [comment]
Glad you're liking shx/shelljs so far :smile: 

In the case of curl, I would recommend just installing that yourself (it's a binary, and supports both windows and unix if I recall). Otherwise, I think there are npm modules for curl functionality which shouldn't be too hard to use.
