### ISSUE TITLE
sed does not replace in files

### ISSUE THREAD

**Issue by FredLackeyOfficial** [shelljs/shx#158]
No combination of regex or separate strings works for replacing a string in a series of files.

My goal is to change this file...

    module.exports = function (sequelize, DataTypes) {
      return sequelize.define('address_line', {
      });
    };

... to this ...

    module.exports = (sequelize, DataTypes) => {
      return sequelize.define('address_line', {
      });
    };

The command I'm currently using is:

    shx sed -i 's/function (sequelize, DataTypes)/(sequelize, DataTypes) =>/g' ./data/models/**/*.js

It is currently used within the `package.json` file of a Node project:

    {
      "scripts": {
        "models:fix:function": "shx sed -i 's/function (sequelize, DataTypes)/(sequelize, DataTypes) =>/g' ./data/models/**/*.js"
      }
    }

Please explain the correct syntax.

**Comment by nfischer** [comment]
You need to escape the `(` and `)` in the regex part.

```sh
shx sed 's/function \(sequelize, DataTypes\)/(sequelize, DataTypes) =>/g' ...
```

`shx sed` isn't quite a drop-in replacement for unix `sed`. Contributions are welcome, however.

**Comment by nfischer** [comment]
^ Closing for now, since I think I've answered your question. For the time being, I think it's easier to just live with `shx sed`'s quirks until we can make a more-complete `shell.sed()` in ShellJS.
