### ISSUE TITLE
rm -rf random fails on windows

### ISSUE THREAD

**Issue by chadbr** [shelljs/shx#160]
Hello --

I've recently starting using shx on Windows.

When I try to use `shx rm -rf dist`

I get random failures
```
rm: could not remove directory (code ENOTEMPTY): dist/data
```

am I doing something wrong?

Thanks, Chad

**Comment by nfischer** [comment]
Not sure what this would be. What's the relation between `somedir` and `dist/data`? Which of these directories actually exist on disk? Anything weird with permissions, or any chance these are links/shortcuts?

**Comment by chadbr** [comment]
@nfischer sorry - I should have just left it `dist` -- I was trying to generalize and only got 1/2 way.

Anyway - the output is just typescript compilation output. Javascrtipt / json / etc. in a directory structure that corresponds to the source files. 

Nothing special. And as I say, it's very random. Maybe ... 20% of the time it happens?

Is there maybe a debug or detailed trace flag I can set to possibly catch some more detail on the failures on the exceptions? I haven't looked at the code at all (yet?)...

Thanks, Chad

**Comment by nfischer** [comment]
Could you try writing a shelljs script like so?

```js
const shell = require('shelljs');
shell.config.fatal = true;
shell.rm('-rf', 'dist');
```

**Comment by chadbr** [comment]
I'm going to close this for now -- I'm about 90% sure it's vscode locking up folders...

Sorry for the noise!

**Comment by chadbr** [comment]
Great tool by the way!

**Comment by nfischer** [comment]
Glad you find it helpful! If this repros again, feel free to reopen.
