### ISSUE TITLE
Can I replace bash prompt with shx ? If so, how ?

### ISSUE THREAD

**Issue by meepeek** [shelljs/shx#171]

**Comment by nfischer** [comment]
shx isn't a complete shell replacement, it's just a cross-platform reimplementation of standard unix commands.

If you're interested in a replacement shell, you could look at [cash](https://github.com/dthree/cash) (a POSIX-like shell implemented in JavaScript), zsh (a popular bash alternative), or fish (a non-POSIX-compliant shell).
