### ISSUE TITLE
suggestion - expose commands directly (`ls` instead of `shx ls`)

### ISSUE THREAD

**Issue by akashmugu** [shelljs/shx#174]
exposing commands directly (e.g. `ls`) along with (or instead of) via [shx](https://github.com/shelljs/shx/blob/master/package.json#L6) (e.g. `shx ls`) will make adding and removing shx extremely easy and literally a one line change

`npm i -D shx`

many small teams still use *nix commands directly in scripts if all the members use *nix. if a newly joined team member uses windows, just add shx to the devDependencies and magic, it all just works

let me know if makes sense. i'd be happy to create a pr

**Comment by nfischer** [comment]
Not a high priority, as this is already offered by https://github.com/dthree/cash.
