### ISSUE TITLE
cp command with --parents?

### ISSUE THREAD

**Issue by basickarl** [shelljs/shx#175]
I'm trying to do the following:
`cp **/*.csv --parents ../target`

Keep the hierarchy in other words, is this possible in shx as of now?

**Comment by nfischer** [comment]
We don't support that option. It appears to be non-POSIX, so it's not high priority.

I think you could write a script with [ShellJS](https://github.com/shelljs/shelljs) to achieve the same effect. I didn't test this, but something like this might work:

```javascript
var destinationDir = '../target'; // or whatever your destination is
shell.ls('**/*.csv').forEach(csvFile => {
  // csvFile should be of the form "subdir/othersubdir/file.csv", where "subdir"
  // is a subdir of the current working directory
  var outputDir = path.join(destinationDir, path.dirname(csvFile));
  shell.mkdir('-p', outputDir);
  shell.cp(csvFile, outputDir);
});
```

Let me know if that works for you (or if you need to make edits).

**Comment by basickarl** [comment]
Thanks for the quick response!
