### ISSUE TITLE
Unable to output escaped double quotes using shx echo

### ISSUE THREAD

**Issue by doberkofler** [shelljs/shx#178]
The following example shows that `shx echo` does not seem to output the escaped double quotes (at least) on the Windows platform:

```json
{
  "name": "shx-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "shx echo Usage: node runSelenium.js \"**/BasePage--test.ts\""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "shx": "^0.3.2"
  }
}
```

**Comment by nfischer** [comment]
That's equivalent to running any of the following in your shell:

```sh
$ shx echo Usage: node runSelenium.js "**/BasePage--test.ts"
```

If you want quote literals, you need:

```sh
$ shx echo Usage: node runSelenium.js '"**/BasePage--test.ts"'
```

Which translates to:

```json
{
  "scripts": {
    "test": "shx echo Usage: node runSelenium.js '\"**/BasePage--test.ts\"'"
  }
}
```

**Comment by doberkofler** [comment]
Thank you. This works on macOS and Linux but on the Windows platform the output wrongly shows the single quotes: `Usage: node scripts/runSelenium.js '**/BasePage--test.ts'`.

**Comment by nfischer** [comment]
Then you'll need to rewrite it with double-quotes (that's a Windows issue, before shx ever starts executing). I think this should work cross-platform:

```json
{
  "scripts": {
    "test": "shx echo Usage: node runSelenium.js \"\\\"**/BasePage--test.ts\\\"\""
  }
}
```

**Comment by doberkofler** [comment]
Perfect. Thank you!
