### ISSUE TITLE
Npm package should always have a main module

### ISSUE THREAD

**Issue by codejamninja** [shelljs/shx#180]
The package.json is missing the `main` property. Because this is a cli, I understand why it was neglected, but it can create problems, for example if I am running `require.resolve('shx')`.

**Comment by nfischer** [comment]
Why would you try to require shx? We intentionally don't support this case. If you want to require a library in your own code, you should use ShellJS.

**Comment by codejamninja** [comment]
I'm sure there are many reasons to require `shx` aside from the reason why I need to. I need to find the path to the shx module, and `require.resolve('shx')` is the way to do that, except it does not work without `"main"`.

**Comment by nfischer** [comment]
Why do you need the path to the module? Npm is responsible for adding the executable to the `$PATH`, both for npm lifecycle scripts and for global installs (`npm install -g`).

**Comment by nfischer** [comment]
https://github.com/sindresorhus/clipboard-cli/blob/master/package.json is a CLI which does not support `require`'ing

**Comment by codejamninja** [comment]
@nfischer ok thanks for the clarity.
