### ISSUE TITLE
rsync

### ISSUE THREAD

**Issue by aminya** [shelljs/shx#183]
Adding rsync would be nice

**Comment by nfischer** [comment]
Are there particular features you need which `cp` doesn't offer?

**Comment by aminya** [comment]
https://dev.to/wolfiton/difference-between-cp-and-rsync-dk3

**Comment by nfischer** [comment]
Not sure if we can reach the same level of performance. `-p` option is tracked in https://github.com/shelljs/shelljs/issues/771. Let's consider this a duplicate of that issue for now.
