### ISSUE TITLE
Why not directly overwrite these commands of cp/rm/mv but place them as subcommands of shx?

### ISSUE THREAD

**Issue by rxliuli** [shelljs/shx#188]
Is there any problem with overwriting? It seems to be easier to use

**Comment by nfischer** [comment]
That's not a goal of this project. This is mainly focused on portable commands for npm package scripts. This is a case where it's useful to have shell-like commands but it's OK if it's slightly verbose.

If you want drop-in replacements for unix commands, you can try https://github.com/dthree/cash.
