### ISSUE TITLE
Unable to install with npm

### ISSUE THREAD

**Issue by kirly-af** [shelljs/shx#24]
I tried to install shx with npm (globaly, locally, as dep, as devDep) both linux and windows machines. But it breaks during linking. It looks like it does not find `lib/cli.js` (see the log below).
```
npm install shelljs/shx
```

npm-debug.log
```
1095 verbose about to build /tmp/node_modules/shx/node_modules/shelljs
1096 info build /tmp/node_modules/shx/node_modules/shelljs
1097 info linkStuff shelljs@0.6.0
1098 silly linkStuff shelljs@0.6.0 has /tmp/node_modules/shx/node_modules as its parent node_modules
1099 verbose linkBins shelljs@0.6.0
1100 verbose link bins [ { shjs: './bin/shjs' },
1100 verbose link bins   '/tmp/node_modules/shx/node_modules/.bin',
1100 verbose link bins   false ]
1101 verbose linkMans shelljs@0.6.0
1102 verbose rebuildBundles shelljs@0.6.0
1103 verbose rebuildBundles [ 'glob', 'interpret', 'rechoir' ]
1104 silly gentlyRm /tmp/node_modules/shx/node_modules/.bin/shjs is being purged
1105 verbose gentlyRm don't care about contents; nuking /tmp/node_modules/shx/node_modules/.bin/shjs
1106 info install shelljs@0.6.0
1107 info postinstall shelljs@0.6.0
1108 verbose unlock done using /home/kirly/.npm/_locks/shelljs-4afc8c83066b6587.lock for /tmp/node_modules/shx/node_modules/shelljs
1109 verbose about to build /tmp/node_modules/shx
1110 info build /tmp/node_modules/shx
1111 info linkStuff shx@0.0.1
1112 silly linkStuff shx@0.0.1 has /tmp/node_modules as its parent node_modules
1113 verbose linkBins shx@0.0.1
1114 verbose link bins [ { shx: 'lib/cli.js' }, '/tmp/node_modules/.bin', false ]
1115 verbose linkMans shx@0.0.1
1116 verbose rebuildBundles shx@0.0.1
1117 verbose rebuildBundles [ '.bin', 'shelljs' ]
1118 verbose unlock done using /home/kirly/.npm/_locks/shx-f2158f07ac2468a2.lock for /tmp/node_modules/shx
1119 verbose stack Error: ENOENT, chmod '/tmp/node_modules/shx/lib/cli.js'
1119 verbose stack     at Error (native)
1120 verbose cwd /tmp
1121 error Linux 3.16.0-4-amd64
1122 error argv "/usr/bin/node" "/usr/bin/npm" "i" "-D" "shelljs/shx"
1123 error node v0.12.8
1124 error npm  v2.14.9
1125 error path /tmp/node_modules/shx/lib/cli.js
1126 error code ENOENT
1127 error errno -2
1128 error enoent ENOENT, chmod '/tmp/node_modules/shx/lib/cli.js'
1128 error enoent This is most likely not a problem with npm itself
1128 error enoent and is related to npm not being able to find a file.
1129 verbose exit [ -2, true ]
1130 verbose unbuild node_modules/shx
1131 info preuninstall shx@0.0.1
1132 info uninstall shx@0.0.1
1133 verbose unbuild rmStuff shx@0.0.1 from /tmp/node_modules
1134 silly gentlyRm /tmp/node_modules/.bin/shx is being gently removed
1135 silly gentlyRm verifying /tmp is an npm working directory
1136 silly gentlyRm containing path /tmp is under npm's control, in /tmp
1137 silly gentlyRm deletion target /tmp/node_modules/.bin/shx is under /tmp
1138 verbose gentlyRm vacuuming from /tmp/node_modules/.bin/shx up to /tmp
1139 info postuninstall shx@0.0.1
1140 silly gentlyRm /tmp/node_modules/shx is being purged from base /tmp
1141 verbose gentlyRm don't care about contents; nuking /tmp/node_modules/shx
1142 silly vacuum-fs purging /tmp/node_modules/shx
1143 silly vacuum-fs removing /tmp/node_modules
1144 silly vacuum-fs finished vacuuming up to /tmp
```

**Comment by nfischer** [comment]
This is unfortunately by design. This is something that I disagree with, since I think it deters contributors (`npm install` is always my go-to command for starting a project).

The lib folder has to be built with `npm run dev` first.

I'm in favor of just committing build files, since it makes installing from github a breeze, helping out contributors immensely (unless `npm` stops complaining, which would be even better).

**Comment by levithomason** [comment]
I've added a PR to include the built assets with the NPM package, I still don't think we should include them on GH though.  It will bloat our PRs and cause larger histories.

This also won't be an issue once we publish to NPM.  In the interim, we can add some README help for this.

**Comment by nfischer** [comment]
@levithomason This is still an issue for developers I think. If I'm getting started with shx, what's my first command after I clone the repo? `npm install` seems to fail, and I'm pretty sure `npm run dev` would fail as well (no deps installed).

**Comment by levithomason** [comment]
I think we're talking about two different things.  Let me make sure I've understood this correctly.

### Cloning
Running `git clone ...` and then `npm install` inside the locally cloned repo _should_ work perfectly fine.  There should be no errors and the `lib` folder should also be built.  If this is not the case, there is a bug.

### NPM install from GH
However, attempting to install `shx` _with npm from github as a registry_ `npm install shelljs/shx` will not work, by design.  This is because the `postinstall` hook is not triggered by NPM when you `npm install` from a github repo (known npm bug).  Whereas, it _is_ triggered when you install from the NPM registry.  So, we're talking about:

```
npm install shelljs/shx
# vs
npm install shx  (once published
```

These are completely unrelated to cloning the repo and running `npm install` though.

I don't believe there are any errors with cloning.  To fix the NPM install from GH confusion, I've opened #26.

Please let me know if I'm overlooking anything here.

**Comment by nfischer** [comment]
I'll try out cloning again. Last time I tried, it was broken.

**Comment by kirly-af** [comment]
Thank you for your quick answer.
@levithomason is right.
I failed to add `shx` to one of my projects dependencies (basically to avoid writing a shelljs script for only one `cp`). I understood that this is related to the fact it not published on npm yet.

FYI, **git clone + npm install works fine** (I was doing some tests on the build).

To answer @nfischer, from a developer point of view, I would say that anyway, as long as only one command is necessary and that it is referenced in the README, it should not be a problem.
So I would definitely not mind if the build is not included in the repo.

**Comment by levithomason** [comment]
Here is what I get:

```shell
[system] in src/
› git clone git@github.com:shelljs/shx.git
Cloning into 'shx'...
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 129 (delta 3), reused 0 (delta 0), pack-reused 120
Receiving objects: 100% (129/129), 20.67 KiB | 0 bytes/s, done.
Resolving deltas: 100% (49/49), done.
Checking connectivity... done.

[system] in src/
› cd shx

[system] in shx/ on master
› npm i

> fsevents@1.0.11 install /Users/levithomason/src/shx/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/levithomason/src/shx/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> shx@0.0.1 postinstall /Users/levithomason/src/shx
> npm run build

> shx@0.0.1 prebuild /Users/levithomason/src/shx
> rimraf lib

> shx@0.0.1 build /Users/levithomason/src/shx
> babel src -d lib

src/cli.js -> lib/cli.js
src/printCmdRet.js -> lib/printCmdRet.js
src/shx.js -> lib/shx.js
shx@0.0.1 /Users/levithomason/src/shx
├─┬ ava@0.11.0
│ ├── arr-flatten@1.0.1
...

[system] in shx/ on master
› ls
LICENSE  MAINTAINERS  README.md  lib/  node_modules/  package.json  src/  test/
```

Everything seems to work as it should.  Clone, install, and initial build.  I've also added install from github instructions to the readme.  Note, all this will go away the instant we first publish to NPM.

@kirly-af thanks for the report and follow up, let me know if you run into any further issues and we'll get you fixed up.

**Comment by nfischer** [comment]
Just ran this against PR #21:

```bash
$ cd shx/
$ npm i # after a long time, this fails
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! path /home/nate/PR_21/node_modules/shx/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/nate/PR_21/node_modules/shx/lib/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/nate/PR_21/node_modules/shx/lib/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nate/PR_21/node_modules/shx/npm-debug.log
$ echo $?
254
$ ls # no lib/ folder
LICENSE  MAINTAINERS  node_modules  npm-debug.log  package.json  README.md  src  test

$ npm -v
3.5.2
$ node -v
v5.3.0
$ uname -mrs
Linux 4.2.0-35-generic x86_64
```

My system info is at the end.

**Comment by nfischer** [comment]
This seems to work against master, but #21 is 2 commits ahead (it isn't missing anything in master). Does this not work for other branches?

**Comment by levithomason** [comment]
Hm, branch shouldn't matter.  Though, I'm of the mind we shouldn't put much time into fixing this in this way.  Once we have an npm module, that will cover the grand majority of cases.  To cover the other cases, we can simplify this by pushing built assets to a `dist` branch or something.  Then the npm install from github instructions would just be:

```shell
npm i shelljs/shx#dist
```

**Comment by nfischer** [comment]
Ok, I figured out the issue. It has to do with whether or not the cloned folder is inside the folder `node_modules/`. If it's inside that folder, then it'll try to create the symlink `node_modules/.bin/shx -> ../shx/lib/cli.js`. I imagine it also does something like `chmod +x` in there, which would fail since `lib/cli.js` doesn't exist.

I was cloning into `node_modules/shx/`, which caused the issue. This wouldn't affect many other people though, so I'll make a workaround.

**Comment by kirly-af** [comment]
This is the same issue as when installing via npm. Maybe you should consider removing the `bin` field from the `package.son` until it is published on npm.
You could then specify it on a possible `dist` branch as @levithomason suggested.

**Comment by levithomason** [comment]
@kirly-af `shx` is now available on npm:

```shell
npm i shx -D
```

**Comment by kirly-af** [comment]
Thanks for keeping me up to date, great stuff !
