### ISSUE TITLE
use shx for npm script

### ISSUE THREAD

**Issue by gasolin** [shelljs/shx#29]
I'm curious the possibility if shx could be a better alternative to run npm scripts in platform independent way

**Comment by ariporad** [comment]
Hi @gasolin!

That's exactly why we invented `shx`, we wanted a way to use `shelljs` in npm scripts.

Once we release the first version of `shx`, you'll be able to do something like this:

```json
{
  "scripts": {
    "do:something": "shx rm -rf build dist; shx echo "Done!"
  }
}
```

**Comment by levithomason** [comment]
You've hit it on the head ;) Closing this for good house keeping, feel free to open if there are any further questions.

**Comment by gasolin** [comment]
Looking forward it!

**Comment by levithomason** [comment]
@gasolin `shx` is now available on npm:

```shell
npm i shx -D
```

**Comment by gasolin** [comment]
Thanks! 

In the initial test, I found shx does not work in npm script (compare to rimraf and mkdirp)
might be the path issue.

(installed via `npm install --save-dev shx`)

**Comment by levithomason** [comment]
Thanks @gasolin, could you open a new issue with steps to reproduce?

**Comment by nfischer** [comment]
@levithomason please see #44

**Comment by gasolin** [comment]
now it works, thanks!
