### ISSUE TITLE
Codecov.io repo settings

### ISSUE THREAD

**Issue by levithomason** [shelljs/shx#35]
@ariporad it looks like I don't have complete access to shx.  I'm missing the settings tab.  Guessing this is why I also cannot setup coverage requirements for PRs.  Could you grant me this perm or setup the repo?

What needs done:

- [x] add repo to codecov.io
- [x] add PR coverage status / requirement
- [ ] add codecov.yml

>Here's the current badge for reference:
>[![codecov](https://codecov.io/gh/shelljs/shx/branch/master/graph/badge.svg)](https://codecov.io/gh/shelljs/shx)

**Comment by nfischer** [comment]
@levithomason perms should be fixed now.

**Comment by levithomason** [comment]
💥 thanks

**Comment by nfischer** [comment]
Is there a way to also get the coverage to run as part of the posttest?

**Comment by levithomason** [comment]
Yep, though, why would we want to do this?

**Comment by nfischer** [comment]
I see `npm test` as a way for contributors to check their local changes before submitting a PR. Just like how we have linting as part of our `npm test` (if someone writes code in a different style, we'd like to catch that early on), it might be nice to output coverage results at the end (to warn people early on if they make a coverage-reducing change).

This is similar to how [cash](https://github.com/dthree/cash) is set up, and I found it useful there. Reducing coverage doesn't make the test fail, but it does output the results at least.

**Comment by levithomason** [comment]
Got it, sounds good.  See #38

**Comment by levithomason** [comment]
Looks like we got what we need with the defaults, no yml required for now. Closing as done.
