### ISSUE TITLE
npm install shx

### ISSUE THREAD

**Issue by backspaces** [shelljs/shx#40]
.. doesn't work. Nor does npm install shelljs expose shx.

How do I do an npm install -D of shx?

**Comment by levithomason** [comment]
It is not yet published on NPM ;)  We're moving very close to the first publish.

**Comment by backspaces** [comment]
so is there a way to use shelljs in package.json scripts instead, as one liners?

**Comment by levithomason** [comment]
`shx` is the util you'd need to do this.  There is no easy way to use it until it is published on NPM.  We should have it out very soon.

Note, if you're feeling extra adventurous and really want it _now_ you _could_ technically clone this repo, run a build, and point to that.  However, it is certainly not a recommended approach.

**Comment by backspaces** [comment]
Thanks, great explanation. It's a *great* idea for npm run scripts. Hope all goes well.

**Comment by backspaces** [comment]
ok to leave this open, so when it's on npm I'll get a notification when you announce here?

**Comment by levithomason** [comment]
Sure, I'll close this via #41.

**Comment by levithomason** [comment]
@backspaces `shx` is now available on npm:

```shell
npm i shx -D
```
