### ISSUE TITLE
cd can't work, so we should output a warning

### ISSUE THREAD

**Issue by nfischer** [shelljs/shx#6]
`shx cd` can't ever work (a child process can't modify its parent process's working directory, for security reasons). We should output this as a warning, or just make `shx cd` invalid.

**Comment by nfischer** [comment]
Also, this is also the case with `pushd` and `popd`, I believe.

**Comment by ariporad** [comment]
Hmm...

How does normal cd work?

**Comment by nfischer** [comment]
```Bash
$ pwd
/home/nate
$ cd .. # cd actually works, since it's a shell-builtin
$ pwd
/home/
$ shx cd nate/ # this appears to succeed
$ shx pwd # but since `shx cd` is run as a separate process, it can't change the cwd after it returns
/home/
$ pwd
/home/
```

ShellJS `cd()` works while we're inside the same node process. As soon as node exits, it jumps back to the directory we started from.

**Comment by nfischer** [comment]
Other things that don't really make sense to expose:

 - cd
 - pushd
 - popd
 - dirs (there's no way to build the directory stack)
 - set
 - .to()
 - .toEnd()
 - exit (`shx exit 0` is equivalent to unix `true`. It differs from unix `exit 0` in that it doesn't actually terminate the current shell)
 - exec (what's the point?)

**Comment by levithomason** [comment]
These are great points.  Perhaps it makes sense to implement only a subset of ShellJS commands for the initial release?

**Comment by nfischer** [comment]
I think a blacklist is the best way to go. We can blacklist the commands above (we can probably skip over .to() and .toEnd()), and allow executing the others (that are in shelljs).

Or we can just use one whitelist of the commands I didn't list (ex. ls, rm, cp, sed, etc). @levithomason @ariporad What do you guys think?

**Comment by ariporad** [comment]
Personally, I vote blacklist. Seems simpler.

**Comment by nfischer** [comment]
And if something falls in the blacklist, what should we do? Output a warning, like `Warning: 'shx cd' is not supported`?

**Comment by ariporad** [comment]
That's what I'd do.

Thanks! Ari
On Tue, Mar 8, 2016 at 6:15 PM, Nate Fischer <notifications@github.com> wrote:
And if something falls in the blacklist, what should we do? Output a warning,
like Warning: 'shx cd' is not supported ?

—
Reply to this email directly or view it on GitHub
[https://github.com/shelljs/shx/issues/6#issuecomment-194073029] .[https://github.com/notifications/beacon/ABu7pH0aYmlzV34KmUJP257g6tgmFG-iks5pri04gaJpZM4HsKo3.gif]

**Comment by nfischer** [comment]
SGTM

**Comment by nfischer** [comment]
Check out #8. I haven't tested this (the build system seems broken).

**Comment by levithomason** [comment]
@nfischer can you give some repro steps, expected result, and actual result for the build issue you're having? I'll get a fix up.

**Comment by nfischer** [comment]
@levithomason 

```bash
$ cd shx/
$ npm run dev

# in another terminal, same directory
$ ./lib/cli.js echo hello world
module.js:328
    throw err;
    ^

Error: Cannot find module './parseArgs'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/nate/programming/shx/lib/cli.js:5:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by nfischer** [comment]
For expected result, I would expect that to output "hello world."

**Comment by levithomason** [comment]
Thanks, see #9 for the fix.
