### ISSUE TITLE
Consider using publish-please

### ISSUE THREAD

**Issue by levithomason** [shelljs/shx#60]
https://github.com/inikulin/publish-please

Cc @nfischer, we may want to use this package for super solid releases. Does security checks and guards against using regular npm release. 

I might write "is logged in" and "has permission" checks for it if I start using it.

**Comment by ariporad** [comment]
This looks really cool! I'll open a pr tonight.

Thanks! Ari
On Wed, May 18, 2016 at 8:09 AM, Levi Thomason <notifications@github.com> wrote:
https://github.com/inikulin/publish-please [https://github.com/inikulin/publish-please]

Cc @nfischer [https://github.com/nfischer] , we may want to use this package for super solid releases. Does security checks and guards against using regular npm release.

I might write "is logged in" and "has permission" checks for it if I start using it.

**Comment by ariporad** [comment]
This looks really cool!

**Comment by levithomason** [comment]
We now have a script to iterate on and no other pain points around this.  Going to close this for now.
