### ISSUE TITLE
Generic NUL output redirect

### ISSUE THREAD

**Issue by kirly-af** [shelljs/shx#61]
It would be really convenient to have a kind of generic way to redirect output to:

* `/dev/null` (unix)
* `NUL` (batch)
* `$null` (powershell)

I am trying to think about a syntax that would not be too heavy. Maybe an option like `--null`.
What are your thoughts ?

**Comment by ariporad** [comment]
Hmm... This is interesting. @nfisher: thoughts?

Thanks! Ari
On Fri, Jun 3, 2016 at 7:47 AM, Alexandre <notifications@github.com> wrote:
It would be really convenient to have a kind of generic way to redirect output to:

 * /dev/null (unix)
 * NUL (batch)
 * $null (powershell)

I am trying to think about a syntax that would not be too heavy. Maybe an option like --null .
What are your thoughts ?

**Comment by nfischer** [comment]
Use `config.silent` please.

I was working on a syntax for specifying options on a command-by-command basis

**Comment by nfischer** [comment]
Oh, whoops. Just realized this was shx, not shelljs. In that case, we'd probably need to implement this as `--silent` on the `shx` command itself, perhaps looking like `shx --silent rm foo bar`.

We should implement this to allow arbitrary `config` attributes to become `shx` options, such as `config.verbose` and `config.globOptions`.

**Comment by levithomason** [comment]
>We should implement this to allow arbitrary config attributes to become shx options, such as config.verbose and config.globOptions.

👍
