### ISSUE TITLE
cp -n should not produce errors if file exists

### ISSUE THREAD

**Issue by kirly-af** [shelljs/shx#67]
``` sh
$> ls
fileA  fileB
$> shx cp -n fileA fileB
cp: dest file already exists: fileB
$> echo $?
130
$> cp -n fileA fileB # no output
$> echo $?
0 # no error
```

This is annoying when `shx cp -n` is used in a npm script as the script will then stop.

**Comment by nfischer** [comment]
Just confirmed this. I'm going to close this issue (since it isn't an issue with `shx`), and open an issue against ShellJS.

Thanks @kirly-af!

**Comment by nfischer** [comment]
@kirly-af This'll be fixed by shelljs/shelljs#466, if you want to take a look.

**Comment by nfischer** [comment]
@kirly-af re-downloading `shx` should fix the issue, since the new version of shelljs has this bug fix.

**Comment by kirly-af** [comment]
@nfischer: good ! thanks for notifying me :wink:
