### ISSUE TITLE
Using sed

### ISSUE THREAD

**Issue by buildbreakdo** [shelljs/shx#74]
Is it possible to use sed in a npm run command? If so, could an example be provided? #

**Comment by nfischer** [comment]
@buildbreakdo Thanks for pointing this out! It seems to me like we should take extra care to make sure `shx sed` uses the same syntax as standard unix `sed`. I'll add some unit tests for this to make sure and get back to you.

**Comment by buildbreakdo** [comment]
@nfischer Impressive response time, thanks! See your pull request, awesome work, look forward to using it!

**Comment by nfischer** [comment]
@buildbreakdo This should be in v0.1.3 available on npm.

**Comment by buildbreakdo** [comment]
@nfischer Thanks for this!
