### ISSUE TITLE
Add -u flag  support for cp  

### ISSUE THREAD

**Issue by ilja903** [shelljs/shx#82]
Hello!

It would be great if someone could add -u flag support for cp command.

Right now output is following:

cp: option not recognized: u

Thanks in advance.

**Comment by nfischer** [comment]
@ilja903 could you please reopen this as an issue against shelljs proper? That's where we add features for this sort of thing. This should be possible though. Thanks!

**Comment by ilja903** [comment]
Hi!

Reopened it here: https://github.com/shelljs/shelljs/issues/526

Maybe we should close this issue?

Thanks!

**Comment by nfischer** [comment]
Looks perfect! I'll see if we can look into adding support in ShellJS. Closing this issue for now, so we can continue discussion on the other thread.
