### ISSUE TITLE
List usb devices

### ISSUE THREAD

**Issue by jdnichollsc** [shelljs/shx#84]
Hi guys,

What is the way to check the usb devices connected with shelljs?

Can I use **libusb**?

Thanks in advance, Nicholls

**Comment by nfischer** [comment]
It looks like there are node modules that can handle that sort of thing. I would recommend using those instead of relying on shelljs for that (we have no "list USB" command). Feel free to close this issue if that answers your question

**Comment by jdnichollsc** [comment]
Thanks my friend 👍
