### ISSUE TITLE
chore: add node v7 to CI

### ISSUE THREAD

**Issue by nfischer** [shelljs/shx#90]
v7 is available on `nvm` now, so we should make sure it's added to CI when possible:
- [ ] Travis
- [ ] Appveyor (not sure if it's available yet)

@levithomason can take this, otherwise I'll get to it in a few days.

**Comment by levithomason** [comment]
@nfischer Please consider me on hold for this project.  I have not current usage or need for it and am tied with other work.  Apologies for the lack of availability.

**Comment by nfischer** [comment]
Sure thing
